EXEC := test_vector3f test_vector4f test_vector3i test_vector4i
BINDIR :=bin/
SRCDIR := src/
FILES := $(addsuffix .c, $(EXEC))
FILES := $(addprefix $(SRCDIR), $(FILES))
EXEC := $(addprefix $(BINDIR), $(EXEC))
CXX := gcc
CFLAGS := -Wall -Wextra -Wall
LIBSD := -L .. -L libft
LIB := -lm -lftx -lft
LIBFT := libft.a
LIBFTX := libftx.a
INCLUDE := -I ../includes -I .

all: $(LIBFTX) $(LIBFT) $(EXEC)

$(LIBFT):
	
	git submodule update --init --remote
	make -C libft

$(LIBFTX):
	make -C ..

$(BINDIR):
	mkdir -p bin

.PHONY:

$(EXEC) : $(BINDIR)% : $(SRCDIR)%.c $(BINDIR)
	$(CXX) $(CFLAGS) -o$@ $< $(INCLUDE) $(LIBSD) $(LIB)

clean:
	rm -rf $(EXEC)

re: clean all

fclean: clean
	make fclean -C ..
	make fclean -C libft
	#run: $(EXEC)
#	chmod 755 $(EXEC)
#	./test_vector3f.exe
#	./test_vector4f.exe
#	./test_vector3i.exe
#	./test_vector4i.exe
